INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1000, 'CARRO');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'MOTO');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'CAMINHÃO');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1000, 'FORD');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'VOLKSWAGEN');

INSERT INTO PRODUCT (ID, NAME, QUANTITY_AVAILABLE, FK_CATEGORY, FK_SUPPLIER) VALUES (1000, 'CORCEL', 10, 1000, 1000);
INSERT INTO PRODUCT (ID, NAME, QUANTITY_AVAILABLE, FK_CATEGORY, FK_SUPPLIER) VALUES (1001, 'GOL', 5, 1000, 1001);
INSERT INTO PRODUCT (ID, NAME, QUANTITY_AVAILABLE, FK_CATEGORY, FK_SUPPLIER) VALUES (1002, 'TITAN', 2, 1002, 1001);